In [1]:
#Load the dataset

import pandas as pd

 

dataset = pd.read_csv('hate_speech.csv') 

dataset.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [2]:
dataset.shape

dataset.label.value_counts()

0    3000
1    2242
Name: label, dtype: int64

In [3]:
for index, tweet in enumerate(dataset["tweet"][10:15]):
    print(index+1,"-",tweet)

1 -  â #ireland consumer price index (mom) climbed from previous 0.2% to 0.5% in may   #blog #silver #gold #forex
2 - we are so selfish. #orlando #standwithorlando #pulseshooting #orlandoshooting #biggerproblems #selfish #heabreaking   #values #love #
3 - i get to see my daddy today!!   #80days #gettingfed
4 - ouch...junior is angryð#got7 #junior #yugyoem   #omg
5 - i am thankful for having a paner. #thankful #positive

In [4]:
import re
#Clean text from noise
def clean_text(text):
    #Filter to allow only alphabets
    text = re.sub(r'[^a-zA-Z\']', ' ', text)
    #Remove Unicode characters
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    #Convert to lowercase to maintain consistency
    text = text.lower()  
    return text

In [5]:
dataset['clean_text'] = dataset.tweet.apply(lambda x: clean_text(x))

In [6]:
dataset.head(10)

,id,label,tweet,clean_text
0,1,0,@user when a father is dysfunctional and is s...,user when a father is dysfunctional and is s...
1,2,0,@user @user thanks for #lyft credit i can't us...,user user thanks for lyft credit i can't us...
2,3,0,bihday your majesty,bihday your majesty
3,4,0,#model i love u take with u all the time in ...,model i love u take with u all the time in ...
4,5,0,factsguide: society now #motivation,factsguide society now motivation
5,6,0,[2/2] huge fan fare and big talking before the...,huge fan fare and big talking before the...
6,7,0,@user camping tomorrow @user @user @user @use...,user camping tomorrow user user user use...
7,8,0,the next school year is the year for exams.ð...,the next school year is the year for exams ...
8,9,0,we won!!! love the land!!! #allin #cavs #champ...,we won love the land allin cavs champ...
9,10,0,@user @user welcome here ! i'm it's so #gr...,user user welcome here i'm it's so gr...

In [8]:
#Load the dataset

import pandas as pd

 

dataset = pd.read_csv('hate_speech.csv') 

dataset.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [9]:
for index, tweet in enumerate(dataset["tweet"][10:15]):

    print(index+1,"-",tweet)

1 -  â #ireland consumer price index (mom) climbed from previous 0.2% to 0.5% in may   #blog #silver #gold #forex
2 - we are so selfish. #orlando #standwithorlando #pulseshooting #orlandoshooting #biggerproblems #selfish #heabreaking   #values #love #
3 - i get to see my daddy today!!   #80days #gettingfed
4 - ouch...junior is angryð#got7 #junior #yugyoem   #omg
5 - i am thankful for having a paner. #thankful #positive

In [10]:
import re
#Clean text from noise
def clean_text(text):
    #Filter to allow only alphabets
    text = re.sub(r'[^a-zA-Z\']', ' ', text)
    #Remove Unicode characters
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    #Convert to lowercase to maintain consistency
    text = text.lower()

In [11]:
dataset['clean_text'] = dataset.tweet.apply(lambda x: clean_text(x))

In [19]:
dataset.head(10)

   id  label                                              tweet clean_text
0   1      0   @user when a father is dysfunctional and is s...       None
1   2      0  @user @user thanks for #lyft credit i can't us...       None
2   3      0                                bihday your majesty       None
3   4      0  #model   i love u take with u all the time in ...       None
4   5      0             factsguide: society now    #motivation       None
5   6      0  [2/2] huge fan fare and big talking before the...       None
6   7      0   @user camping tomorrow @user @user @user @use...       None
7   8      0  the next school year is the year for exams.ð...       None
8   9      0  we won!!! love the land!!! #allin #cavs #champ...       None
9  10      0   @user @user welcome here !  i'm   it's so #gr...       None

In [17]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()
def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(strip_accents=None,

                        lowercase=False,

                        preprocessor=None,

                        tokenizer=tokenizer_porter,

                        use_idf=True,

                        norm='l2',

                        smooth_idf=True)

X = tfidf.fit_transform(dataset['clean_text'])

X = X.toarray()

y = dataset.label.values

AttributeError: 'NoneType' object has no attribute 'split'